joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

# Trajectory controllers

AL_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - AL_coxa_joint
    - AL_femur_joint
    - AL_tibia_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.5
    AL_coxa_joint:
      trajectory: 0.1
      goal: 0.5
    AL_femur_joint:
      trajectory: 0.1
      goal: 0.5
    AL_tibia_joint:
      trajectory: 0.1
      goal: 0.5

AR_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - AR_coxa_joint
    - AR_femur_joint
    - AR_tibia_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.5
    AR_coxa_joint:
      trajectory: 0.1
      goal: 0.5
    AR_femur_joint:
      trajectory: 0.1
      goal: 0.5
    AR_tibia_joint:
      trajectory: 0.1
      goal: 0.5

BL_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - BL_coxa_joint
    - BL_femur_joint
    - BL_tibia_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.5
    BL_coxa_joint:
      trajectory: 0.1
      goal: 0.5
    BL_femur_joint:
      trajectory: 0.1
      goal: 0.5
    BL_tibia_joint:
      trajectory: 0.1
      goal: 0.5

BR_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - BR_coxa_joint
    - BR_femur_joint
    - BR_tibia_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.5
    BR_coxa_joint:
      trajectory: 0.1
      goal: 0.5
    BR_femur_joint:
      trajectory: 0.1
      goal: 0.5
    BR_tibia_joint:
      trajectory: 0.1
      goal: 0.5

CL_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - CL_coxa_joint
    - CL_femur_joint
    - CL_tibia_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.5
    CL_coxa_joint:
      trajectory: 0.1
      goal: 0.5
    CL_femur_joint:
      trajectory: 0.1
      goal: 0.5
    CL_tibia_joint:
      trajectory: 0.1
      goal: 0.5

CR_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - CR_coxa_joint
    - CR_femur_joint
    - CR_tibia_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.5
    CR_coxa_joint:
      trajectory: 0.1
      goal: 0.5
    CR_femur_joint:
      trajectory: 0.1
      goal: 0.5
    CR_tibia_joint:
      trajectory: 0.1
      goal: 0.5

